name       : jxrlib
version    : 0.2.4
release    : 2
source     :
    - https://github.com/glencoesoftware/jxrlib/archive/v0.2.4.tar.gz : 324af02e341bcb9e3b31a6d6892f47231f95f9f87ab4fe7645be619dcaf965a7
license    : BSD-2-Clause
component  : multimedia.graphics
summary    : Open source implementation of jpegxr
description: |
    An open source implementation of the jpegxr image format standard.
builddeps  :
    - openjdk-11-devel
    - swig
setup      : |
    %patch -p1 < $pkgfiles/usecmake.patch
    %cmake
build      : |
    %make SHARED=1 PREFIX=/usr
install    : |
    %make_install DIR_INSTALL=$installdir
